project/config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.i18n import JavaScriptCatalog
from django.conf.urls.static import static
from django.conf import settings
from pyha import decorator, views


urlpatterns = [
    url(r'^', include('pyha.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(domain='djangojs', packages=['pyha']),
        name='javascript-catalog'),
]

urlpatterns += decorator.required(decorator.admin_required_and_force_english, [
    url(r'^{0}/logout/?$'.format(settings.SECRET_ADMIN_SUB_DIR), views.logout.logout),
    url(r'^{0}/'.format(settings.SECRET_ADMIN_SUB_DIR), admin.site.urls)
])

project/pyha/urls.py
from django.conf.urls import url
from django.conf import settings
from django.views.generic import RedirectView
from config.timers import *
from pyha.views import api, api_statistics, api_docs, index, requestform, requestview, logout, ajax, usersettings

app_name = 'pyha'
urlpatterns = [
    url(r'^pyha/?$', index.pyha, name='pyha'),
    url(r'^/?$', index.index, name='root'),
    url(r'^index/?$', index.pyha, name='index'),
    url(r'^login/?$', index.index, name='login'),
    url(r'^groupdeleterequest/?$', index.group_delete_request, name='group_delete_request'),
    url(r'^logout/?$', logout.logout, name='logout'),
    url(r'^settings/?$', usersettings.usersettings, name='usersettings'),
    url(r'^ajax/getCollection/?$', ajax.get_collection_ajax, name='get_collection_ajax'),
    url(r'^ajax/getSummary/?$', ajax.get_summary_ajax, name='get_summary_ajax'),
    url(r'^ajax/createContact/?$', ajax.create_contact_ajax, name='create_contact_ajax'),
    url(r'^ajax/removeCollection/?$', ajax.remove_collection_ajax, name='remove_collection_ajax'),
    url(r'^ajax/getDescription/?$', ajax.get_description_ajax, name='get_description_ajax'),
    url(r'^ajax/setDescription/?$', ajax.set_description_ajax, name='set_description_ajax'),
    url(r'^ajax/getRequestList/?$', index.get_request_list_ajax, name='get_request_list_ajax'),
    url(r'^approve/?$', requestform.approve_terms, name='approve'),
    url(r'^request/[1-9][0-9]*/?$', requestview.show_request, name='show_request'),
    url(r'^description/?$', requestview.change_description, name='change_description'),
    url(r'^answer/?$', requestview.answer, name='answer'),
    url(r'^question/?$', requestview.question, name='question'),
    url(r'^groupanswer/?$', requestview.group_answer, name='group_answer'),
    url(r'^information/?$', requestview.information, name='information'),
    url(r'^chatEntryFileDownload/?$', requestview.chat_entry_file_download, name='chat_entry_file_download'),
    url(r'^commentHandler/?$', requestview.comment_handler, name='comment_handler'),
    url(r'^sendEmail/?$', requestview.send_email, name='send_email'),
    url(r'^initializeDownload/?$', requestview.initialize_download, name='initializeDownload'),
    url(r'^downloadLink/?$', ajax.download_link, name='requestDownload'),
    url(r'^gisDownloadStatus/(?P<download_id>[^/]+)/?$', ajax.gis_download_status, name='gis_download_status'),
    url(r'^gisDownloadOutput/(?P<download_id>[^/]+)/?$', ajax.gis_download_output, name='gis_download_output'),
    url(r'^apiKey/?$', ajax.get_api_key, name='get_api_key'),
    url(r'^saveUserSettings/?$', usersettings.save_user_settings, name='save_user_settings'),
    url(r'^savePyhaSettings/?$', usersettings.save_pyha_settings, name='save_pyha_settings'),
    url(r'^newpdf/?$', api.new_pdf, name='newpdf'),
    url(r'^api/request/?$', api.receiver, name='receiver'),
    url(r'^api/download/(?P<link>[^/]+)/?$', api.download, name='download'),
    url(r'^api/newcount/?$', api.new_count, name='new_count'),
    url(r'^{0}/?$'.format(settings.SECRET_STATUS_SUB_DIR), api.status, name='status'),
    url(r'^api/swagger.json$', api_docs.api_spec, name='api_spec'),
    url(r'^api/docs/?$', api_docs.api_docs, name='swagger-ui'),
    url(r'^api/statistics/countByYear/?$', api_statistics.request_count_by_year, name='count_by_year'),
    url(r'^api/statistics/collectionCounts/?$', api_statistics.collection_counts, name='collection_counts'),
    url(r'^api/statistics/reasonCounts/?$', api_statistics.request_reason_counts, name='reason_counts'),
    url(r'^api/statistics/reasonPhraseCounts/?$', api_statistics.request_reason_phrase_counts, name='reason_phrase_counts'),
    url(r'^api/statistics/partyInvolvementCounts/?$', api_statistics.request_party_involvement_counts, name='party_involvement_counts'),
    url(r'^role/?$', logout.change_role, name='change_role'),
    url(r'^freezeRequest/?$', requestview.freeze, name='freeze'),
    url(r'^refreshCollectionsCache/?$', requestview.refresh_collections_cache, name='refresh_collections_cache'),
    url(r'^lang/?$', logout.change_lang, name='set_language'),
    url(r'^handler-manual.pdf$', RedirectView.as_view(
        url='https://cdn.laji.fi/files/pyha/Aineistopyyntöjärjestelmä_ohje_käsittelijoille_2022.pdf',
        permanent=False
    ), name='handler_manual')
]

project/pyha/views/ajax.py
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, StreamingHttpResponse
from django.shortcuts import render
from django.conf import settings
from pyha.database import create_request_view_context, check_all_collections_removed, is_downloadable
from pyha.localization import check_language
from pyha.login import logged_in, is_allowed_to_view, is_request_owner, is_admin_frozen
from pyha.models import Request, Collection, StatusEnum
from pyha.log_utils import changed_by_session_user
import requests
from http import HTTPStatus

from pyha.view_utils import get_default_laji_api_headers


def download_link(http_request):
    if http_request.method == 'POST':
        if not logged_in(http_request):
            return HttpResponse(status=HTTPStatus.UNAUTHORIZED)
        requestId = http_request.POST.get('requestid')
        if not is_request_owner(http_request, requestId):
            return HttpResponse(status=HTTPStatus.FORBIDDEN)
        userRequest = Request.objects.get(id=requestId)
        if is_admin_frozen(http_request, userRequest):
            return HttpResponse(status=HTTPStatus.LOCKED)
        if not (userRequest.status == 8 and is_downloadable(http_request, userRequest)):
            return HttpResponse(status=HTTPStatus.BAD_REQUEST)

        userRequest.downloaded = True
        userRequest.changedBy = changed_by_session_user(http_request)
        userRequest.save()

        file_type = http_request.POST.get('fileType', '?')
        geometry = http_request.POST.get('geometry', '?')
        CRS = http_request.POST.get('CRS', '?')
        laji_id = userRequest.lajiId
        person_token = http_request.session['token']

        if file_type == 'GIS':
            params = {
                'geometryType': geometry,
                'crs': CRS
            }
            headers = get_default_laji_api_headers(http_request)
            url = '{}geo-convert/{}'.format(settings.LAJIAPI_URL, laji_id)
            r = requests.get(url, params=params, headers=headers)

            if not r.ok:
                return _get_geoconvert_error_response(r)

            return HttpResponseRedirect(reverse('pyha:gis_download_status', args=(r.json(),)))
        else:
            link = '{}{}?personToken={}'.format(settings.LAJIDOW_URL, laji_id, person_token)
            return JsonResponse({'status': 'complete', 'downloadUrl': link})

    return HttpResponse(status=HTTPStatus.METHOD_NOT_ALLOWED)


def gis_download_status(http_request, download_id):
    if http_request.method == 'GET':
        headers = get_default_laji_api_headers(http_request)
        url = '{}geo-convert/status/{}'.format(settings.LAJIAPI_URL, download_id)
        r = requests.get(url, headers=headers)

        if not r.ok:
            return _get_geoconvert_error_response(r)

        status_obj = r.json()
        status = status_obj['status']
        response = {
            'status': status,
            'progressPercent': status_obj['progress_percent'],
            'statusUrl': reverse('pyha:gis_download_status', args=(download_id,)),
            'downloadUrl': reverse('pyha:gis_download_output', args=(download_id,)) if status == 'complete' else None
        }

        return JsonResponse(response)

    return HttpResponse(status=HTTPStatus.METHOD_NOT_ALLOWED)


def gis_download_output(http_request, download_id):
    if http_request.method == 'GET':
        headers = get_default_laji_api_headers(http_request)
        url = '{}geo-convert/output/{}'.format(settings.LAJIAPI_URL, download_id)
        r = requests.get(url, headers=headers, stream=True)

        response = StreamingHttpResponse(
            r.raw,
            content_type=r.headers.get('content-type'),
            status=r.status_code,
            reason=r.reason
        )

        content_disposition = r.headers.get('content-disposition')
        if content_disposition:
            response['Content-Disposition'] = content_disposition

        return response

    return HttpResponse(status=HTTPStatus.METHOD_NOT_ALLOWED)


def get_api_key(http_request):
    if http_request.method == 'POST':
        if not logged_in(http_request):
            return HttpResponse(status=HTTPStatus.UNAUTHORIZED)
        requestId = http_request.POST.get('requestid')
        if not is_request_owner(http_request, requestId):
            return HttpResponse(status=HTTPStatus.FORBIDDEN)
        userRequest = Request.objects.get(id=requestId)
        if is_admin_frozen(http_request, userRequest):
            return HttpResponse(status=HTTPStatus.LOCKED)
        if not (userRequest.status == 8 and is_downloadable(http_request, userRequest)):
            return HttpResponse(status=HTTPStatus.BAD_REQUEST)

        userRequest.downloaded = True
        userRequest.changedBy = changed_by_session_user(http_request)
        userRequest.save()

        laji_id = userRequest.lajiId
        person_token = http_request.session['token']

        response = requests.get('{}warehouse/api-keys/{}'.format(settings.LAJIAPI_URL, laji_id),
                                params={'personToken': person_token, 'access_token': settings.LAJIAPI_TOKEN},
                                timeout=settings.SECRET_TIMEOUT_PERIOD
                                )
        if not response.ok:
            return HttpResponse(status=HTTPStatus.BAD_GATEWAY)

        api_key = response.json()
        if 'apiKey' not in api_key:
            return HttpResponse(status=HTTPStatus.NOT_FOUND)

        return JsonResponse({
            'apiKey': api_key['apiKey'],
            'apiKeyExpires': api_key['apiKeyExpires']
        })

    return HttpResponse(status=HTTPStatus.METHOD_NOT_ALLOWED)


def get_description_ajax(http_request):
    if http_request.method == 'POST' and http_request.POST.get('requestid'):
        if check_language(http_request):
            return HttpResponse(reverse(http_request.get_full_path()), status=310)
        if not logged_in(http_request):
            return HttpResponse(reverse('pyha:root'), status=310)
        requestId = http_request.POST.get('requestid')
        if not is_allowed_to_view(http_request, requestId):
            return HttpResponse(reverse('pyha:root'), status=310)
        userRequest = Request.objects.get(id=requestId)
        context = create_request_view_context(requestId, http_request, userRequest)
        return render(http_request, 'pyha/base/ajax/requestheader.html', context)
    return HttpResponse(reverse('pyha:root'), status=310)


def set_description_ajax(http_request):
    if http_request.method == 'POST':
        if not logged_in(http_request):
            return HttpResponse(reverse('pyha:root'), status=310)
        requestId = http_request.POST.get('requestid')
        if not is_request_owner(http_request, requestId):
            return HttpResponse(reverse('pyha:root'), status=310)
        userRequest = Request.objects.get(id=requestId)
        if is_admin_frozen(http_request, userRequest):
            return HttpResponse(reverse('pyha:root'), status=310)
        userRequest.description = http_request.POST.get('description')
        userRequest.changedBy = changed_by_session_user(http_request)
        userRequest.save()
        return HttpResponse(status=200)
    return HttpResponse(reverse('pyha:root'), status=310)


def get_collection_ajax(http_request):
    if http_request.method == 'POST' and http_request.POST.get('requestid'):
        if check_language(http_request):
            return HttpResponse(reverse(http_request.get_full_path()), status=310)
        if not logged_in(http_request):
            return HttpResponse(reverse('pyha:root'), status=310)
        requestId = http_request.POST.get('requestid')
        if not is_allowed_to_view(http_request, requestId):
            return HttpResponse(reverse('pyha:root'), status=310)
        userRequest = Request.objects.get(id=requestId)
        if is_admin_frozen(http_request, userRequest):
            return HttpResponse(reverse('pyha:root'), status=310)
        if(userRequest.status == StatusEnum.APPROVETERMS_WAIT):
            context = create_request_view_context(requestId, http_request, userRequest)
            return render(http_request, 'pyha/requestform/ajax/requestformcollection.html', context)
    return HttpResponse(reverse('pyha:root'), status=310)


def get_summary_ajax(http_request):
    if http_request.method == 'POST' and http_request.POST.get('requestid'):
        if check_language(http_request):
            return HttpResponse(reverse(http_request.get_full_path()), status=310)
        if not logged_in(http_request):
            return HttpResponse(reverse('pyha:root'), status=310)
        requestId = http_request.POST.get('requestid')
        if not is_allowed_to_view(http_request, requestId):
            return HttpResponse(reverse('pyha:root'), status=310)
        userRequest = Request.objects.get(id=requestId)
        if is_admin_frozen(http_request, userRequest):
            return HttpResponse(reverse('pyha:root'), status=310)
        if(userRequest.status == StatusEnum.APPROVETERMS_WAIT):
            context = create_request_view_context(requestId, http_request, userRequest)
            return render(http_request, 'pyha/requestform/ajax/requestformsummary.html', context)
    return HttpResponse(reverse('pyha:root'), status=310)


def create_contact_ajax(http_request):
    if http_request.method == 'POST' and http_request.POST.get('requestid') and http_request.POST.get('id'):
        if check_language(http_request):
            return HttpResponse(reverse(http_request.get_full_path()), status=310)
        if not logged_in(http_request):
            return HttpResponse(reverse('pyha:root'), status=310)
        requestId = http_request.POST.get('requestid')
        if not is_request_owner(http_request, requestId):
            return HttpResponse(reverse('pyha:root'), status=310)
        userRequest = Request.objects.get(id=requestId)

project/pyha/views/api_docs.py
from apispec import APISpec
from apispec import BasePlugin
from apispec.yaml_utils import load_operations_from_docstring
from django.http import JsonResponse
from django.shortcuts import render
from django.conf import settings
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from pyha.views.api_statistics import request_count_by_year, collection_counts, request_reason_counts, \
    request_reason_phrase_counts, request_party_involvement_counts


class PyhaPlugin(BasePlugin):
    def path_helper(self, path, operations, func, **kwargs):
        """Path helper that parses docstrings for operations. Adds a
        ``func`` parameter to `apispec.APISpec.path`.
        """
        operations.update(load_operations_from_docstring(func.__doc__))


def get_spec():
    spec = APISpec(
        title="Pyha API",
        version="1.0.0",
        openapi_version="3.0.2",
        plugins=[PyhaPlugin()]
    )

    spec.path(path=reverse('pyha:count_by_year'), func=request_count_by_year)
    spec.path(path=reverse('pyha:collection_counts'), func=collection_counts)
    spec.path(path=reverse('pyha:reason_counts'), func=request_reason_counts)
    spec.path(path=reverse('pyha:reason_phrase_counts'), func=request_reason_phrase_counts)
    spec.path(path=reverse('pyha:party_involvement_counts'), func=request_party_involvement_counts)

    return spec


@csrf_exempt
def api_spec(http_request):
    return JsonResponse(get_spec().to_dict())


@csrf_exempt
def api_docs(http_request):
    return render(http_request, 'pyha/swagger/swaggerui.html', {'static': settings.STA_URL, 'version': settings.VERSION})

project/pyha/templates/pyha/base/base.html
<!DOCTYPE html>
{% load i18n %}
{% load static %}
{% block start_script %}
{% endblock %}

<html lang="fi">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
		<meta name="description" content="">
		<meta name="author" content="">
		<link rel="icon" href="https://cdn.laji.fi/images/icons/favicon.ico">

		<title>{{ title }}</title>


		<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->
		<link rel="stylesheet" href="{{ static }}pyha/bootstrap-3.3.7/css/bootstrap.min.css">
		<!-- Bootstrap CSS local fallback -->
		<!-- Optional theme -->
		<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->
		<link rel="stylesheet" href="{{ static }}pyha/bootstrap-3.3.7/css/bootstrap-theme.min.css">

		<!-- <link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css"> -->
		<link rel="stylesheet" href="{{ static }}pyha/bootstrap-dataTables/dataTables.bootstrap.min.css">
		<link rel="stylesheet" href="{{ static }}pyha/css/bootstrap-multiselect.css" type="text/css"/>
		<link rel="stylesheet" type="text/css" href="{{ static }}pyha/styles.css?v={{version}}" >
		<link rel="stylesheet" type="text/css" href="{{ static }}pyha/font.css?v={{version}}" >
		<link rel="stylesheet" type="text/css" href="{{ static }}pyha/tabs/tabs.css?v={{version}}" >

		{% if request.session.current_user_role == 'admin' %}
		<link rel="stylesheet" type="text/css" href="{{ static }}pyha/admin.css?v={{version}}" >
		{% elif request.session.current_user_role == 'handler' %}
		<link rel="stylesheet" type="text/css" href="{{ static }}pyha/handler.css?v={{version}}" >
		{% endif %}
	</head>

	<body>
		<nav class="navbar navbar-custom navbar-fixed-top">
		    <div class="container-fluid">
		      <div class="navbar-header">
		        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
		          <span class="sr-only">{% trans "Toggle_navigation" %}</span>
		          <span class="icon-bar"></span>
		          <span class="icon-bar"></span>
		          <span class="icon-bar"></span>
		        </button>
		        <span class="navbar-brand nohover">LAJI.FI</span>
		      </div>
		      {% if username %}
		      <div id="navbar" class="collapse navbar-collapse">
		        <ul class="nav navbar-nav">
		          <li><a href="{% url 'pyha:index' %}">{% trans "all_requests" %}</a></li>
		        </ul>
		        {% if 'admin' in request.session.current_user_role %}
		        <ul class="nav navbar-nav">
		          <li><a href="{% url 'admin:index' %}">{% trans "admin_site" %}</a></li>
		        </ul>
		        <ul class="nav navbar-nav">
		          <li><a href="{% url 'pyha:usersettings' %}">{% trans "admin_settings" %}</a></li>
		        </ul>
		        {% endif %}
		        <ul class="nav navbar-nav navbar-right">
		        <li><a class="nohover" >{{username}} <span class="glyphicon glyphicon-user"></span></a></li>
				{% if 'handler' in request.session.user_roles or 'admin' in request.session.user_roles %}
				<li>
				<div class="dropdown">
				<form id='role_form' action="{% url 'pyha:change_role' %}" method="post"
		            data-currenturl='{{ request.path }}'
		            data-currentfullurl='{{ request.get_full_path }}'>

				<button type="button" onclick="roleFunction()" class="dropbtn">{% if request.session.current_user_role == 'admin' %}{% trans "admin" %}{% elif request.session.current_user_role == 'handler' %}{% trans "handler" %}{% else %}{% trans "user" %}{% endif %} {% csrf_token %}<span class="glyphicon glyphicon-eye-open"></span></button>
				<div id="roleDropdown" class="dropdown-content">
	              	<a onclick='roleSubmit("user")' name="role" id="role">{% trans "user" %}</a>
	              	{% if 'handler' in request.session.user_roles %}<a onclick='roleSubmit("handler")' name="role" id="role">{% trans "handler" %}</a>{% endif %}
	              	{% if 'admin' in request.session.user_roles %}<a onclick='roleSubmit("admin")' name="role" id="role">{% trans "admin" %}</a>{% endif %}
				</div>
				</div>
				<input type="hidden" id="next" name="next" value={{request.path}}>
				<input id='role_form_select' name="role" type="hidden" value="">
				</form>
				</li>
				{% endif %}
		        <li><a href="{% url 'pyha:logout' %}">{% trans "logout" %} <span class="glyphicon glyphicon-log-out"></span></a></li>
		        {% get_current_language as LANGUAGE %}
				<li>
					<div class="dropdown">
					<form id='language_form' action="{% url 'pyha:set_language' %}" method="post"
						data-currenturl='{{ request.path }}'
						data-currentfullurl='{{ request.get_full_path }}'>
					<button type="button" onclick="showLangDropdown()" class="dropbtn"><span class="glyphicon glyphicon-globe"></span> {{LANGUAGE|upper}}{% csrf_token %}</button>
						<div id="langDropdown" class="dropdown-content" style="left: -50%;">
						  {% get_available_languages as LANGUAGES %}
						  {% get_language_info_list for LANGUAGES as languages %}

						  {% for language in languages %}
							{% if not LANGUAGE == language.code %}
							  <a onclick='submit("{{ language.code }}")' name="code" id="code">
								  {% if language.code == 'fi' %}
								  {% trans "set_lang_fi" %}
								  {% elif language.code == 'sv' %}
								  {% trans "set_lang_sv" %}
								  {% elif language.code == 'en' %}
								  {% trans "set_lang_en" %}
								  {% endif %}
							  </a>
							  {% endif %}
						  {% endfor %}

						</div>
					<input id='language_form_select' name="language" type="hidden" value="">
					<input type="hidden" id="next" name="next" value={{request.get_full_path}}>
					</form>
					</div>
				</li>
				{% if request.session.current_user_role == 'handler' or request.session.current_user_role == 'admin' %}
		        <li><a href="{% url 'pyha:handler_manual' %}" target="_blank">{% trans "manual" %} <span class="glyphicon glyphicon-question-sign"></span></a></li>
				{% endif %}
				<li><a href="https://laji.fi/about/{% if language.code == 'en' %}848{% else %}713{% endif %}" target="_blank">{% trans "privacy_policy" %}</a></li>
		        </ul>
		      {% endif %}
		    </div>
		   </div>

		</nav>
		<div id="toastbox_error" class="toastbox error">
			<span class="glyphicon glyphicon-remove large-thin-glyphicon-error toast-glyphicon"> </span>
			<span id="toastbox_error_msg"></span>
		</div>
		<div id="toastbox_positive" class="toastbox positive">
			<span class="glyphicon glyphicon-ok large-thin-glyphicon-positive toast-glyphicon"> </span>
			<span id="toastbox_positive_msg"></span>
		</div>
		<div id="toastbox_info" class="toastbox info">
			<span class="glyphicon glyphicon-info-sign large-thin-glyphicon-info toast-glyphicon"> </span>
			<span id="toastbox_info_msg"></span>
		</div>
		{% block content %}
		{% endblock %}
		<!-- Bootstrap core JavaScript
		================================================== -->
		<!-- Placed at the end of the document so the pages load faster -->
		<!-- old <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script> -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
		<!-- jQuery local fallback -->
		<script>window.jQuery || document.write('<script src="{{ static }}pyha/jquery-3.1.1/jquery.min.js"><\/script>')</script>

		<!-- Latest compiled and minified JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
		<!-- Bootstrap JS local fallback -->
		<script>if(typeof($.fn.modal) === 'undefined') {document.write('<script src="{{ static }}pyha/bootstrap-3.3.7/js/bootstrap.min.js"><\/script>')}</script>

		<script src="{{ static }}pyha/jquery-dataTables/jquery.dataTables.min.js"></script>
		<script src="{{ static }}pyha/bootstrap-dataTables/dataTables.bootstrap.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.min.js"></script>
		<script src="{{ static }}pyha/js/datetime.js"></script>
		<script src="{{ static }}pyha/js/ellipsis.js"></script>
		<script type="text/javascript" src="{{ static }}pyha/js/bootstrap-multiselect.js"></script>
		<script src="{{ static }}pyha/tabs/tabs.js?v={{version}}"></script>
		<script src="{{ static }}pyha/ajax/ajax.js?v={{version}}"></script>
		  <script>
		function showLangDropdown() {
		    document.getElementById("langDropdown").classList.toggle("show");
		}

		window.onclick = function(event) {
		  if (!event.target.matches('.dropbtn')) {

		    var dropdowns = document.getElementsByClassName("dropdown-content");
		    var i;
		    for (i = 0; i < dropdowns.length; i++) {
		      var openDropdown = dropdowns[i];
		      if (openDropdown.classList.contains('show')) {
		        openDropdown.classList.remove('show');
		      }
		    }
		  }
		}

		function submit(lang) {
			document.getElementById("language_form_select").value = lang
			document.getElementById("language_form").submit()
		}

		function roleFunction() {
		    document.getElementById("roleDropdown").classList.toggle("show");
		}

		function roleSubmit(role) {
			document.getElementById("role_form_select").value = role
			document.getElementById("role_form").submit()
		}

		function showToast(msg, type) {
			var toastBoxMsg = document.getElementById("toastbox_" + type + "_msg");
			toastBoxMsg.innerText = msg;
			var toastBox = document.getElementById("toastbox_" + type);
			setTimeout(function(){ toastBox.classList.add("show");}, 1000);
		    setTimeout(function(){ toastBox.classList.remove("show");}, 7000);
		}

		function showGenericErrorToast() {
			showToast("{% trans 'generic_error' %}", "error");
		}

		</script>

		{% if toast %}
		<script>
			$(document).ready(function(){
				showToast("{{ toast.message }}", "{{ toast.status }}");
			});
		</script>
		{% endif %}
		<script>
			$(document).ready(function(){
			  $('[data-toggle="tooltip"]').tooltip();
			  $('[data-toggle="popover"]').popover();
			});
		</script>

	</body>
</html>
{% block end_script %}
{% endblock %}