project/config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.i18n import JavaScriptCatalog
from django.conf.urls.static import static
from django.conf import settings
from pyha import decorator, views


urlpatterns = [
    url(r'^', include('pyha.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(domain='djangojs', packages=['pyha']),
        name='javascript-catalog'),
]

urlpatterns += decorator.required(decorator.admin_required_and_force_english, [
    url(r'^{0}/logout/?$'.format(settings.SECRET_ADMIN_SUB_DIR), views.logout.logout),
    url(r'^{0}/'.format(settings.SECRET_ADMIN_SUB_DIR), admin.site.urls)
])

project/pyha/urls.py
from django.conf.urls import url
from django.conf import settings
from django.views.generic import RedirectView
from config.timers import *
from pyha.views import api, api_statistics, api_docs, index, requestform, requestview, logout, ajax, usersettings

app_name = 'pyha'
urlpatterns = [
    url(r'^pyha/?$', index.pyha, name='pyha'),
    url(r'^/?$', index.index, name='root'),
    url(r'^index/?$', index.pyha, name='index'),
    url(r'^login/?$', index.index, name='login'),
    url(r'^groupdeleterequest/?$', index.group_delete_request, name='group_delete_request'),
    url(r'^logout/?$', logout.logout, name='logout'),
    url(r'^settings/?$', usersettings.usersettings, name='usersettings'),
    url(r'^ajax/getCollection/?$', ajax.get_collection_ajax, name='get_collection_ajax'),
    url(r'^ajax/getSummary/?$', ajax.get_summary_ajax, name='get_summary_ajax'),
    url(r'^ajax/createContact/?$', ajax.create_contact_ajax, name='create_contact_ajax'),
    url(r'^ajax/removeCollection/?$', ajax.remove_collection_ajax, name='remove_collection_ajax'),
    url(r'^ajax/getDescription/?$', ajax.get_description_ajax, name='get_description_ajax'),
    url(r'^ajax/setDescription/?$', ajax.set_description_ajax, name='set_description_ajax'),
    url(r'^ajax/getRequestList/?$', index.get_request_list_ajax, name='get_request_list_ajax'),
    url(r'^approve/?$', requestform.approve_terms, name='approve'),
    url(r'^request/[1-9][0-9]*/?$', requestview.show_request, name='show_request'),
    url(r'^description/?$', requestview.change_description, name='change_description'),
    url(r'^answer/?$', requestview.answer, name='answer'),
    url(r'^question/?$', requestview.question, name='question'),
    url(r'^groupanswer/?$', requestview.group_answer, name='group_answer'),
    url(r'^information/?$', requestview.information, name='information'),
    url(r'^chatEntryFileDownload/?$', requestview.chat_entry_file_download, name='chat_entry_file_download'),
    url(r'^commentHandler/?$', requestview.comment_handler, name='comment_handler'),
    url(r'^sendEmail/?$', requestview.send_email, name='send_email'),
    url(r'^initializeDownload/?$', requestview.initialize_download, name='initializeDownload'),
    url(r'^downloadLink/?$', ajax.download_link, name='requestDownload'),
    url(r'^gisDownloadStatus/(?P<download_id>[^/]+)/?$', ajax.gis_download_status, name='gis_download_status'),
    url(r'^gisDownloadOutput/(?P<download_id>[^/]+)/?$', ajax.gis_download_output, name='gis_download_output'),
    url(r'^apiKey/?$', ajax.get_api_key, name='get_api_key'),
    url(r'^saveUserSettings/?$', usersettings.save_user_settings, name='save_user_settings'),
    url(r'^savePyhaSettings/?$', usersettings.save_pyha_settings, name='save_pyha_settings'),
    url(r'^newpdf/?$', api.new_pdf, name='newpdf'),
    url(r'^api/request/?$', api.receiver, name='receiver'),
    url(r'^api/download/(?P<link>[^/]+)/?$', api.download, name='download'),
    url(r'^api/newcount/?$', api.new_count, name='new_count'),
    url(r'^{0}/?$'.format(settings.SECRET_STATUS_SUB_DIR), api.status, name='status'),
    url(r'^api/swagger.json$', api_docs.api_spec, name='api_spec'),
    url(r'^api/docs/?$', api_docs.api_docs, name='swagger-ui'),
    url(r'^api/statistics/countByYear/?$', api_statistics.request_count_by_year, name='count_by_year'),
    url(r'^api/statistics/collectionCounts/?$', api_statistics.collection_counts, name='collection_counts'),
    url(r'^api/statistics/reasonCounts/?$', api_statistics.request_reason_counts, name='reason_counts'),
    url(r'^api/statistics/reasonPhraseCounts/?$', api_statistics.request_reason_phrase_counts, name='reason_phrase_counts'),
    url(r'^api/statistics/partyInvolvementCounts/?$', api_statistics.request_party_involvement_counts, name='party_involvement_counts'),
    url(r'^role/?$', logout.change_role, name='change_role'),
    url(r'^freezeRequest/?$', requestview.freeze, name='freeze'),
    url(r'^refreshCollectionsCache/?$', requestview.refresh_collections_cache, name='refresh_collections_cache'),
    url(r'^lang/?$', logout.change_lang, name='set_language'),
    url(r'^handler-manual.pdf$', RedirectView.as_view(
        url='https://cdn.laji.fi/files/pyha/Aineistopyyntöjärjestelmä_ohje_käsittelijoille_2022.pdf',
        permanent=False
    ), name='handler_manual')
]

project/pyha/views/ajax.py
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, StreamingHttpResponse
from django.shortcuts import render
from django.conf import settings
from pyha.database import create_request_view_context, check_all_collections_removed, is_downloadable
from pyha.localization import check_language
from pyha.login import logged_in, is_allowed_to_view, is_request_owner, is_admin_frozen
from pyha.models import Request, Collection, StatusEnum
from pyha.log_utils import changed_by_session_user
import requests
from http import HTTPStatus

from pyha.view_utils import get_default_laji_api_headers


def download_link(http_request):
    if http_request.method == 'POST':
        if not logged_in(http_request):
            return HttpResponse(status=HTTPStatus.UNAUTHORIZED)
        requestId = http_request.POST.get('requestid')
        if not is_request_owner(http_request, requestId):
            return HttpResponse(status=HTTPStatus.FORBIDDEN)
        userRequest = Request.objects.get(id=requestId)
        if is_admin_frozen(http_request, userRequest):
            return HttpResponse(status=HTTPStatus.LOCKED)
        if not (userRequest.status == 8 and is_downloadable(http_request, userRequest)):
            return HttpResponse(status=HTTPStatus.BAD_REQUEST)

        userRequest.downloaded = True
        userRequest.changedBy = changed_by_session_user(http_request)
        userRequest.save()

        file_type = http_request.POST.get('fileType', '?')
        geometry = http_request.POST.get('geometry', '?')
        CRS = http_request.POST.get('CRS', '?')
        laji_id = userRequest.lajiId
        person_token = http_request.session['token']

        if file_type == 'GIS':
            params = {
                'geometryType': geometry,
                'crs': CRS
            }
            headers = get_default_laji_api_headers(http_request)
            url = '{}geo-convert/{}'.format(settings.LAJIAPI_URL, laji_id)
            r = requests.get(url, params=params, headers=headers)

            if not r.ok:
                return _get_geoconvert_error_response(r)

            return HttpResponseRedirect(reverse('pyha:gis_download_status', args=(r.json(),)))
        else:
            link = '{}{}?personToken={}'.format(settings.LAJIDOW_URL, laji_id, person_token)
            return JsonResponse({'status': 'complete', 'downloadUrl': link})

    return HttpResponse(status=HTTPStatus.METHOD_NOT_ALLOWED)


def gis_download_status(http_request, download_id):
    if http_request.method == 'GET':
        headers = get_default_laji_api_headers(http_request)
        url = '{}geo-convert/status/{}'.format(settings.LAJIAPI_URL, download_id)
        r = requests.get(url, headers=headers)

        if not r.ok:
            return _get_geoconvert_error_response(r)

        status_obj = r.json()
        status = status_obj['status']
        response = {
            'status': status,
            'progressPercent': status_obj['progress_percent'],
            'statusUrl': reverse('pyha:gis_download_status', args=(download_id,)),
            'downloadUrl': reverse('pyha:gis_download_output', args=(download_id,)) if status == 'complete' else None
        }

        return JsonResponse(response)

    return HttpResponse(status=HTTPStatus.METHOD_NOT_ALLOWED)


def gis_download_output(http_request, download_id):
    if http_request.method == 'GET':
        headers = get_default_laji_api_headers(http_request)
        url = '{}geo-convert/output/{}'.format(settings.LAJIAPI_URL, download_id)
        r = requests.get(url, headers=headers, stream=True)

        response = StreamingHttpResponse(
            r.raw,
            content_type=r.headers.get('content-type'),
            status=r.status_code,
            reason=r.reason
        )

        content_disposition = r.headers.get('content-disposition')
        if content_disposition:
            response['Content-Disposition'] = content_disposition

        return response

    return HttpResponse(status=HTTPStatus.METHOD_NOT_ALLOWED)


def get_api_key(http_request):
    if http_request.method == 'POST':
        if not logged_in(http_request):
            return HttpResponse(status=HTTPStatus.UNAUTHORIZED)
        requestId = http_request.POST.get('requestid')
        if not is_request_owner(http_request, requestId):
            return HttpResponse(status=HTTPStatus.FORBIDDEN)
        userRequest = Request.objects.get(id=requestId)
        if is_admin_frozen(http_request, userRequest):
            return HttpResponse(status=HTTPStatus.LOCKED)
        if not (userRequest.status == 8 and is_downloadable(http_request, userRequest)):
            return HttpResponse(status=HTTPStatus.BAD_REQUEST)

        userRequest.downloaded = True
        userRequest.changedBy = changed_by_session_user(http_request)
        userRequest.save()

        laji_id = userRequest.lajiId
        person_token = http_request.session['token']

        response = requests.get('{}warehouse/api-keys/{}'.format(settings.LAJIAPI_URL, laji_id),
                                params={'personToken': person_token, 'access_token': settings.LAJIAPI_TOKEN},
                                timeout=settings.SECRET_TIMEOUT_PERIOD
                                )
        if not response.ok:
            return HttpResponse(status=HTTPStatus.BAD_GATEWAY)

        api_key = response.json()
        if 'apiKey' not in api_key:
            return HttpResponse(status=HTTPStatus.NOT_FOUND)

        return JsonResponse({
            'apiKey': api_key['apiKey'],
            'apiKeyExpires': api_key['apiKeyExpires']
        })

    return HttpResponse(status=HTTPStatus.METHOD_NOT_ALLOWED)


def get_description_ajax(http_request):
    if http_request.method == 'POST' and http_request.POST.get('requestid'):
        if check_language(http_request):
            return HttpResponse(reverse(http_request.get_full_path()), status=310)
        if not logged_in(http_request):
            return HttpResponse(reverse('pyha:root'), status=310)
        requestId = http_request.POST.get('requestid')
        if not is_allowed_to_view(http_request, requestId):
            return HttpResponse(reverse('pyha:root'), status=310)
        userRequest = Request.objects.get(id=requestId)
        context = create_request_view_context(requestId, http_request, userRequest)
        return render(http_request, 'pyha/base/ajax/requestheader.html', context)
    return HttpResponse(reverse('pyha:root'), status=310)


def set_description_ajax(http_request):
    if http_request.method == 'POST':
        if not logged_in(http_request):
            return HttpResponse(reverse('pyha:root'), status=310)
        requestId = http_request.POST.get('requestid')
        if not is_request_owner(http_request, requestId):
            return HttpResponse(reverse('pyha:root'), status=310)
        userRequest = Request.objects.get(id=requestId)
        if is_admin_frozen(http_request, userRequest):
            return HttpResponse(reverse('pyha:root'), status=310)
        userRequest.description = http_request.POST.get('description')
        userRequest.changedBy = changed_by_session_user(http_request)
        userRequest.save()
        return HttpResponse(status=200)
    return HttpResponse(reverse('pyha:root'), status=310)


def get_collection_ajax(http_request):
    if http_request.method == 'POST' and http_request.POST.get('requestid'):
        if check_language(http_request):
            return HttpResponse(reverse(http_request.get_full_path()), status=310)
        if not logged_in(http_request):
            return HttpResponse(reverse('pyha:root'), status=310)
        requestId = http_request.POST.get('requestid')
        if not is_allowed_to_view(http_request, requestId):
            return HttpResponse(reverse('pyha:root'), status=310)
        userRequest = Request.objects.get(id=requestId)
        if is_admin_frozen(http_request, userRequest):
            return HttpResponse(reverse('pyha:root'), status=310)
        if(userRequest.status == StatusEnum.APPROVETERMS_WAIT):
            context = create_request_view_context(requestId, http_request, userRequest)
            return render(http_request, 'pyha/requestform/ajax/requestformcollection.html', context)
    return HttpResponse(reverse('pyha:root'), status=310)


def get_summary_ajax(http_request):
    if http_request.method == 'POST' and http_request.POST.get('requestid'):
        if check_language(http_request):
            return HttpResponse(reverse(http_request.get_full_path()), status=310)
        if not logged_in(http_request):
            return HttpResponse(reverse('pyha:root'), status=310)
        requestId = http_request.POST.get('requestid')
        if not is_allowed_to_view(http_request, requestId):
            return HttpResponse(reverse('pyha:root'), status=310)
        userRequest = Request.objects.get(id=requestId)
        if is_admin_frozen(http_request, userRequest):
            return HttpResponse(reverse('pyha:root'), status=310)
        if(userRequest.status == StatusEnum.APPROVETERMS_WAIT):
            context = create_request_view_context(requestId, http_request, userRequest)
            return render(http_request, 'pyha/requestform/ajax/requestformsummary.html', context)
    return HttpResponse(reverse('pyha:root'), status=310)


def create_contact_ajax(http_request):
    if http_request.method == 'POST' and http_request.POST.get('requestid') and http_request.POST.get('id'):
        if check_language(http_request):
            return HttpResponse(reverse(http_request.get_full_path()), status=310)
        if not logged_in(http_request):
            return HttpResponse(reverse('pyha:root'), status=310)
        requestId = http_request.POST.get('requestid')
        if not is_request_owner(http_request, requestId):
            return HttpResponse(reverse('pyha:root'), status=310)
        userRequest = Request.objects.get(id=requestId)

project/pyha/views/api_docs.py
from apispec import APISpec
from apispec import BasePlugin
from apispec.yaml_utils import load_operations_from_docstring
from django.http import JsonResponse
from django.shortcuts import render
from django.conf import settings
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from pyha.views.api_statistics import request_count_by_year, collection_counts, request_reason_counts, \
    request_reason_phrase_counts, request_party_involvement_counts


class PyhaPlugin(BasePlugin):
    def path_helper(self, path, operations, func, **kwargs):
        """Path helper that parses docstrings for operations. Adds a
        ``func`` parameter to `apispec.APISpec.path`.
        """
        operations.update(load_operations_from_docstring(func.__doc__))


def get_spec():
    spec = APISpec(
        title="Pyha API",
        version="1.0.0",
        openapi_version="3.0.2",
        plugins=[PyhaPlugin()]
    )

    spec.path(path=reverse('pyha:count_by_year'), func=request_count_by_year)
    spec.path(path=reverse('pyha:collection_counts'), func=collection_counts)
    spec.path(path=reverse('pyha:reason_counts'), func=request_reason_counts)
    spec.path(path=reverse('pyha:reason_phrase_counts'), func=request_reason_phrase_counts)
    spec.path(path=reverse('pyha:party_involvement_counts'), func=request_party_involvement_counts)

    return spec


@csrf_exempt
def api_spec(http_request):
    return JsonResponse(get_spec().to_dict())


@csrf_exempt
def api_docs(http_request):
    return render(http_request, 'pyha/swagger/swaggerui.html', {'static': settings.STA_URL, 'version': settings.VERSION})

project/pyha/templates/pyha/base/admin/usersettings.html
{% extends "pyha/base/base.html" %}
{% block content %}
{% load i18n %}


<div class="container-fluid">
<div class="row">
	 <div class="col-xs-12">
		<div class="page-header">
		  	<h2>{% trans "admin_settings_header" %}</h2>
		</div>
 		<h3 style="margin-top:50px">{% trans "admin_user_settings" %}<small> ({{ email }}) </small></h3>
 		<form action="{% url 'pyha:save_user_settings' %}" id="settingsform" method="post">
 			<input type="hidden" id="next" name="next" value="{{request.path}}">
 			<p>{% trans "admin_send_me_email_for_new_requests" %}</p>
 			<div class="row">
 				<div class="col-sm-3">
					<select class="form-control" id="email_new_requests" name="email_new_requests">
						<option value="{{email_new_requests_setting.2.0}}" {% if user_settings.emailNewRequests == email_new_requests_setting.2.0 %} selected {% endif %}>{% trans "admin_email_for_none" %}</option>
						<option value="{{email_new_requests_setting.1.0}}" {% if user_settings.emailNewRequests == email_new_requests_setting.1.0 %} selected {% endif %}>{% trans "admin_email_for_missing_handlers" %}</option>
						<option value="{{email_new_requests_setting.0.0}}" {% if user_settings.emailNewRequests == email_new_requests_setting.0.0 %} selected {% endif %}>{% trans "admin_email_for_all" %}</option>
					</select>
				</div>
			</div>
 			<div class="row">
		 		<div class="checkbox col-sm-2">
				    <label>
				      	<input onChange="refreshCustomEmail()" {% if user_settings.customEmailAddress %} checked {% endif %} type="checkbox" id="use_custom_email" name="use_custom_email" value="True"> {% trans "admin_use_custom_email_address" %}
				    </label>
				</div>
			</div>
			<div class="row">
				<div class="form-group col-sm-4">
				    <label class="sr-only" for="InputEmail">Email address</label>
				    <input type="email" class="form-control " id="email_address" name="email_address" placeholder="Email" value="{{ user_settings.customEmailAddress }}">
				    <button style="margin-top:10px;" type="submit" id="submit" name="save" value=1 class="btn btn-default btn-sm" >{% trans "admin_save" %}</button>
				</div>
		   	</div>
	   		{% csrf_token %}
	   </form>
	   <h3 style="margin-top:50px">{% trans "admin_pyha_settings" %} <small style="color:red">{% trans "settings_affect_pyha_not_you_as_as_user" %}</small></h3>

	   <form action="{% url 'pyha:save_pyha_settings' %}" id="settingsform" method="post">
 			<input type="hidden" id="next" name="next" value="{{request.path}}">
 			<p>{% trans "admin_pyha_periodical_event_automation" %}</p>
 			<small style="color:orange">{% trans "admin_periodical_event_automation_settings_work_only_on_in_built_threaded_scheduling_not_cron" %}</small>
 			<div class="row">
		 		<div class="checkbox col-sm-2">
				    <label>
				      	<input {% if pyha_settings.enableDailyHandlerEmail %} checked {% endif %} type="checkbox" id="enable_daily_handler_email" name="enable_daily_handler_email" value="True"> {% trans "admin_enable_daily_handler_email" %}
				    </label>
				</div>
				<p data-toggle="collapse" data-target="#daily_handler_email_information" class="btn btn-default btn-sm" style="margin:10px">{% trans "admin_setting_additional_information" %}</p>
			</div>
			<div style="white-space: pre-line;" id="daily_handler_email_information" class="collapse">
				<div style="padding-bottom: 30px;">
					{% trans "daily_handler_email_information" %}
				</div>
			</div>
			<div class="row">
				<div class="checkbox col-sm-2">
						<label>
								<input {% if pyha_settings.enableDailyRequesterEmail %} checked {% endif %} type="checkbox" id="enable_daily_requester_email" name="enable_daily_requester_email" value="True"> {% trans "admin_enable_daily_requester_email" %}
						</label>
				</div>
				<p data-toggle="collapse" data-target="#daily_requester_email_information" class="btn btn-default btn-sm" style="margin:10px">{% trans "admin_setting_additional_information" %}</p>
			</div>
			<div style="white-space: pre-line;" id="daily_requester_email_information" class="collapse">
				<div style="padding-bottom: 30px;">
					{% trans "daily_requester_email_information" %}
				</div>
			</div>
			<div class="row">
		 		<div class="checkbox col-sm-2">
				    <label>
				      	<input {% if pyha_settings.enableWeeklyMissingHandlersEmail %} checked {% endif %} type="checkbox" id="enable_weekly_missing_handlers_email" name="enable_weekly_missing_handlers_email" value="True"> {% trans "admin_enable_weekly_missing_handlers_email" %}
				    </label>
				</div>
				<p data-toggle="collapse" data-target="#weekly_missing_handlers_email_information" class="btn btn-default btn-sm" style="margin:10px">{% trans "admin_setting_additional_information" %}</p>
			</div>
			<div style="white-space: pre-line;"  id="weekly_missing_handlers_email_information" class="collapse">
				<div style="padding-bottom: 30px;">
					{% trans "weekly_missing_handlers_email_information" %}
				</div>
			</div>
			<div class="row">
		 		<div class="checkbox col-sm-2">
				    <label>
				      	<input {% if pyha_settings.enableDeclineOverdueCollections %} checked {% endif %} type="checkbox" id="enable_auto_decline_overdue" name="enable_auto_decline_overdue" value="True"> {% trans "admin_enable_auto_decline_overdue" %}
				    </label>
				</div>
				<p data-toggle="collapse" data-target="#auto_decline_overdue_information" class="btn btn-default btn-sm" style="margin:10px">{% trans "admin_setting_additional_information" %}</p>
			</div>
			<div style="white-space: pre-line;"  id="auto_decline_overdue_information" class="collapse">
				<div style="padding-bottom: 30px;">
				{% trans "auto_decline_overdue_information" %}
				</div>
			</div>
			<div class="row">
				<div class="form-group col-sm-4">
				    <label>
						<button style="margin-top:10px;" type="submit" id="submit" name="save" value=1 class="btn btn-default btn-sm" >{% trans "admin_save" %}</button>
					</label>
				</div>
			</div>
	   		{% csrf_token %}
	   </form>

	 </div>
</div>
</div>
{% endblock %}

{% block end_script %}
	<script>
		function refreshCustomEmail() {
			var x = document.getElementById('use_custom_email');
			var y = document.getElementById('email_address');
			y.disabled = !x.checked;
			if(!x.checked){
				y.value = "";
			}

		}
	</script>
	<script>
		$(document).ready(function(){
			refreshCustomEmail();
		});
	</script>
{% endblock %}