project/config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.i18n import JavaScriptCatalog
from django.conf.urls.static import static
from django.conf import settings
from pyha import decorator, views


urlpatterns = [
    url(r'^', include('pyha.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(domain='djangojs', packages=['pyha']),
        name='javascript-catalog'),
]

urlpatterns += decorator.required(decorator.admin_required_and_force_english, [
    url(r'^{0}/logout/?$'.format(settings.SECRET_ADMIN_SUB_DIR), views.logout.logout),
    url(r'^{0}/'.format(settings.SECRET_ADMIN_SUB_DIR), admin.site.urls)
])

project/pyha/urls.py
from django.conf.urls import url
from django.conf import settings
from django.views.generic import RedirectView
from config.timers import *
from pyha.views import api, api_statistics, api_docs, index, requestform, requestview, logout, ajax, usersettings

app_name = 'pyha'
urlpatterns = [
    url(r'^pyha/?$', index.pyha, name='pyha'),
    url(r'^/?$', index.index, name='root'),
    url(r'^index/?$', index.pyha, name='index'),
    url(r'^login/?$', index.index, name='login'),
    url(r'^groupdeleterequest/?$', index.group_delete_request, name='group_delete_request'),
    url(r'^logout/?$', logout.logout, name='logout'),
    url(r'^settings/?$', usersettings.usersettings, name='usersettings'),
    url(r'^ajax/getCollection/?$', ajax.get_collection_ajax, name='get_collection_ajax'),
    url(r'^ajax/getSummary/?$', ajax.get_summary_ajax, name='get_summary_ajax'),
    url(r'^ajax/createContact/?$', ajax.create_contact_ajax, name='create_contact_ajax'),
    url(r'^ajax/removeCollection/?$', ajax.remove_collection_ajax, name='remove_collection_ajax'),
    url(r'^ajax/getDescription/?$', ajax.get_description_ajax, name='get_description_ajax'),
    url(r'^ajax/setDescription/?$', ajax.set_description_ajax, name='set_description_ajax'),
    url(r'^ajax/getRequestList/?$', index.get_request_list_ajax, name='get_request_list_ajax'),
    url(r'^approve/?$', requestform.approve_terms, name='approve'),
    url(r'^request/[1-9][0-9]*/?$', requestview.show_request, name='show_request'),
    url(r'^description/?$', requestview.change_description, name='change_description'),
    url(r'^answer/?$', requestview.answer, name='answer'),
    url(r'^question/?$', requestview.question, name='question'),
    url(r'^groupanswer/?$', requestview.group_answer, name='group_answer'),
    url(r'^information/?$', requestview.information, name='information'),
    url(r'^chatEntryFileDownload/?$', requestview.chat_entry_file_download, name='chat_entry_file_download'),
    url(r'^commentHandler/?$', requestview.comment_handler, name='comment_handler'),
    url(r'^sendEmail/?$', requestview.send_email, name='send_email'),
    url(r'^initializeDownload/?$', requestview.initialize_download, name='initializeDownload'),
    url(r'^downloadLink/?$', ajax.download_link, name='requestDownload'),
    url(r'^gisDownloadStatus/(?P<download_id>[^/]+)/?$', ajax.gis_download_status, name='gis_download_status'),
    url(r'^gisDownloadOutput/(?P<download_id>[^/]+)/?$', ajax.gis_download_output, name='gis_download_output'),
    url(r'^apiKey/?$', ajax.get_api_key, name='get_api_key'),
    url(r'^saveUserSettings/?$', usersettings.save_user_settings, name='save_user_settings'),
    url(r'^savePyhaSettings/?$', usersettings.save_pyha_settings, name='save_pyha_settings'),
    url(r'^newpdf/?$', api.new_pdf, name='newpdf'),
    url(r'^api/request/?$', api.receiver, name='receiver'),
    url(r'^api/download/(?P<link>[^/]+)/?$', api.download, name='download'),
    url(r'^api/newcount/?$', api.new_count, name='new_count'),
    url(r'^{0}/?$'.format(settings.SECRET_STATUS_SUB_DIR), api.status, name='status'),
    url(r'^api/swagger.json$', api_docs.api_spec, name='api_spec'),
    url(r'^api/docs/?$', api_docs.api_docs, name='swagger-ui'),
    url(r'^api/statistics/countByYear/?$', api_statistics.request_count_by_year, name='count_by_year'),
    url(r'^api/statistics/collectionCounts/?$', api_statistics.collection_counts, name='collection_counts'),
    url(r'^api/statistics/reasonCounts/?$', api_statistics.request_reason_counts, name='reason_counts'),
    url(r'^api/statistics/reasonPhraseCounts/?$', api_statistics.request_reason_phrase_counts, name='reason_phrase_counts'),
    url(r'^api/statistics/partyInvolvementCounts/?$', api_statistics.request_party_involvement_counts, name='party_involvement_counts'),
    url(r'^role/?$', logout.change_role, name='change_role'),
    url(r'^freezeRequest/?$', requestview.freeze, name='freeze'),
    url(r'^refreshCollectionsCache/?$', requestview.refresh_collections_cache, name='refresh_collections_cache'),
    url(r'^lang/?$', logout.change_lang, name='set_language'),
    url(r'^handler-manual.pdf$', RedirectView.as_view(
        url='https://cdn.laji.fi/files/pyha/Aineistopyyntöjärjestelmä_ohje_käsittelijoille_2022.pdf',
        permanent=False
    ), name='handler_manual')
]

project/pyha/views/ajax.py
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, StreamingHttpResponse
from django.shortcuts import render
from django.conf import settings
from pyha.database import create_request_view_context, check_all_collections_removed, is_downloadable
from pyha.localization import check_language
from pyha.login import logged_in, is_allowed_to_view, is_request_owner, is_admin_frozen
from pyha.models import Request, Collection, StatusEnum
from pyha.log_utils import changed_by_session_user
import requests
from http import HTTPStatus

from pyha.view_utils import get_default_laji_api_headers


def download_link(http_request):
    if http_request.method == 'POST':
        if not logged_in(http_request):
            return HttpResponse(status=HTTPStatus.UNAUTHORIZED)
        requestId = http_request.POST.get('requestid')
        if not is_request_owner(http_request, requestId):
            return HttpResponse(status=HTTPStatus.FORBIDDEN)
        userRequest = Request.objects.get(id=requestId)
        if is_admin_frozen(http_request, userRequest):
            return HttpResponse(status=HTTPStatus.LOCKED)
        if not (userRequest.status == 8 and is_downloadable(http_request, userRequest)):
            return HttpResponse(status=HTTPStatus.BAD_REQUEST)

        userRequest.downloaded = True
        userRequest.changedBy = changed_by_session_user(http_request)
        userRequest.save()

        file_type = http_request.POST.get('fileType', '?')
        geometry = http_request.POST.get('geometry', '?')
        CRS = http_request.POST.get('CRS', '?')
        laji_id = userRequest.lajiId
        person_token = http_request.session['token']

        if file_type == 'GIS':
            params = {
                'geometryType': geometry,
                'crs': CRS
            }
            headers = get_default_laji_api_headers(http_request)
            url = '{}geo-convert/{}'.format(settings.LAJIAPI_URL, laji_id)
            r = requests.get(url, params=params, headers=headers)

            if not r.ok:
                return _get_geoconvert_error_response(r)

            return HttpResponseRedirect(reverse('pyha:gis_download_status', args=(r.json(),)))
        else:
            link = '{}{}?personToken={}'.format(settings.LAJIDOW_URL, laji_id, person_token)
            return JsonResponse({'status': 'complete', 'downloadUrl': link})

    return HttpResponse(status=HTTPStatus.METHOD_NOT_ALLOWED)


def gis_download_status(http_request, download_id):
    if http_request.method == 'GET':
        headers = get_default_laji_api_headers(http_request)
        url = '{}geo-convert/status/{}'.format(settings.LAJIAPI_URL, download_id)
        r = requests.get(url, headers=headers)

        if not r.ok:
            return _get_geoconvert_error_response(r)

        status_obj = r.json()
        status = status_obj['status']
        response = {
            'status': status,
            'progressPercent': status_obj['progress_percent'],
            'statusUrl': reverse('pyha:gis_download_status', args=(download_id,)),
            'downloadUrl': reverse('pyha:gis_download_output', args=(download_id,)) if status == 'complete' else None
        }

        return JsonResponse(response)

    return HttpResponse(status=HTTPStatus.METHOD_NOT_ALLOWED)


def gis_download_output(http_request, download_id):
    if http_request.method == 'GET':
        headers = get_default_laji_api_headers(http_request)
        url = '{}geo-convert/output/{}'.format(settings.LAJIAPI_URL, download_id)
        r = requests.get(url, headers=headers, stream=True)

        response = StreamingHttpResponse(
            r.raw,
            content_type=r.headers.get('content-type'),
            status=r.status_code,
            reason=r.reason
        )

        content_disposition = r.headers.get('content-disposition')
        if content_disposition:
            response['Content-Disposition'] = content_disposition

        return response

    return HttpResponse(status=HTTPStatus.METHOD_NOT_ALLOWED)


def get_api_key(http_request):
    if http_request.method == 'POST':
        if not logged_in(http_request):
            return HttpResponse(status=HTTPStatus.UNAUTHORIZED)
        requestId = http_request.POST.get('requestid')
        if not is_request_owner(http_request, requestId):
            return HttpResponse(status=HTTPStatus.FORBIDDEN)
        userRequest = Request.objects.get(id=requestId)
        if is_admin_frozen(http_request, userRequest):
            return HttpResponse(status=HTTPStatus.LOCKED)
        if not (userRequest.status == 8 and is_downloadable(http_request, userRequest)):
            return HttpResponse(status=HTTPStatus.BAD_REQUEST)

        userRequest.downloaded = True
        userRequest.changedBy = changed_by_session_user(http_request)
        userRequest.save()

        laji_id = userRequest.lajiId
        person_token = http_request.session['token']

        response = requests.get('{}warehouse/api-keys/{}'.format(settings.LAJIAPI_URL, laji_id),
                                params={'personToken': person_token, 'access_token': settings.LAJIAPI_TOKEN},
                                timeout=settings.SECRET_TIMEOUT_PERIOD
                                )
        if not response.ok:
            return HttpResponse(status=HTTPStatus.BAD_GATEWAY)

        api_key = response.json()
        if 'apiKey' not in api_key:
            return HttpResponse(status=HTTPStatus.NOT_FOUND)

        return JsonResponse({
            'apiKey': api_key['apiKey'],
            'apiKeyExpires': api_key['apiKeyExpires']
        })

    return HttpResponse(status=HTTPStatus.METHOD_NOT_ALLOWED)


def get_description_ajax(http_request):
    if http_request.method == 'POST' and http_request.POST.get('requestid'):
        if check_language(http_request):
            return HttpResponse(reverse(http_request.get_full_path()), status=310)
        if not logged_in(http_request):
            return HttpResponse(reverse('pyha:root'), status=310)
        requestId = http_request.POST.get('requestid')
        if not is_allowed_to_view(http_request, requestId):
            return HttpResponse(reverse('pyha:root'), status=310)
        userRequest = Request.objects.get(id=requestId)
        context = create_request_view_context(requestId, http_request, userRequest)
        return render(http_request, 'pyha/base/ajax/requestheader.html', context)
    return HttpResponse(reverse('pyha:root'), status=310)


def set_description_ajax(http_request):
    if http_request.method == 'POST':
        if not logged_in(http_request):
            return HttpResponse(reverse('pyha:root'), status=310)
        requestId = http_request.POST.get('requestid')
        if not is_request_owner(http_request, requestId):
            return HttpResponse(reverse('pyha:root'), status=310)
        userRequest = Request.objects.get(id=requestId)
        if is_admin_frozen(http_request, userRequest):
            return HttpResponse(reverse('pyha:root'), status=310)
        userRequest.description = http_request.POST.get('description')
        userRequest.changedBy = changed_by_session_user(http_request)
        userRequest.save()
        return HttpResponse(status=200)
    return HttpResponse(reverse('pyha:root'), status=310)


def get_collection_ajax(http_request):
    if http_request.method == 'POST' and http_request.POST.get('requestid'):
        if check_language(http_request):
            return HttpResponse(reverse(http_request.get_full_path()), status=310)
        if not logged_in(http_request):
            return HttpResponse(reverse('pyha:root'), status=310)
        requestId = http_request.POST.get('requestid')
        if not is_allowed_to_view(http_request, requestId):
            return HttpResponse(reverse('pyha:root'), status=310)
        userRequest = Request.objects.get(id=requestId)
        if is_admin_frozen(http_request, userRequest):
            return HttpResponse(reverse('pyha:root'), status=310)
        if(userRequest.status == StatusEnum.APPROVETERMS_WAIT):
            context = create_request_view_context(requestId, http_request, userRequest)
            return render(http_request, 'pyha/requestform/ajax/requestformcollection.html', context)
    return HttpResponse(reverse('pyha:root'), status=310)


def get_summary_ajax(http_request):
    if http_request.method == 'POST' and http_request.POST.get('requestid'):
        if check_language(http_request):
            return HttpResponse(reverse(http_request.get_full_path()), status=310)
        if not logged_in(http_request):
            return HttpResponse(reverse('pyha:root'), status=310)
        requestId = http_request.POST.get('requestid')
        if not is_allowed_to_view(http_request, requestId):
            return HttpResponse(reverse('pyha:root'), status=310)
        userRequest = Request.objects.get(id=requestId)
        if is_admin_frozen(http_request, userRequest):
            return HttpResponse(reverse('pyha:root'), status=310)
        if(userRequest.status == StatusEnum.APPROVETERMS_WAIT):
            context = create_request_view_context(requestId, http_request, userRequest)
            return render(http_request, 'pyha/requestform/ajax/requestformsummary.html', context)
    return HttpResponse(reverse('pyha:root'), status=310)


def create_contact_ajax(http_request):
    if http_request.method == 'POST' and http_request.POST.get('requestid') and http_request.POST.get('id'):
        if check_language(http_request):
            return HttpResponse(reverse(http_request.get_full_path()), status=310)
        if not logged_in(http_request):
            return HttpResponse(reverse('pyha:root'), status=310)
        requestId = http_request.POST.get('requestid')
        if not is_request_owner(http_request, requestId):
            return HttpResponse(reverse('pyha:root'), status=310)
        userRequest = Request.objects.get(id=requestId)

project/pyha/views/api_docs.py
from apispec import APISpec
from apispec import BasePlugin
from apispec.yaml_utils import load_operations_from_docstring
from django.http import JsonResponse
from django.shortcuts import render
from django.conf import settings
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from pyha.views.api_statistics import request_count_by_year, collection_counts, request_reason_counts, \
    request_reason_phrase_counts, request_party_involvement_counts


class PyhaPlugin(BasePlugin):
    def path_helper(self, path, operations, func, **kwargs):
        """Path helper that parses docstrings for operations. Adds a
        ``func`` parameter to `apispec.APISpec.path`.
        """
        operations.update(load_operations_from_docstring(func.__doc__))


def get_spec():
    spec = APISpec(
        title="Pyha API",
        version="1.0.0",
        openapi_version="3.0.2",
        plugins=[PyhaPlugin()]
    )

    spec.path(path=reverse('pyha:count_by_year'), func=request_count_by_year)
    spec.path(path=reverse('pyha:collection_counts'), func=collection_counts)
    spec.path(path=reverse('pyha:reason_counts'), func=request_reason_counts)
    spec.path(path=reverse('pyha:reason_phrase_counts'), func=request_reason_phrase_counts)
    spec.path(path=reverse('pyha:party_involvement_counts'), func=request_party_involvement_counts)

    return spec


@csrf_exempt
def api_spec(http_request):
    return JsonResponse(get_spec().to_dict())


@csrf_exempt
def api_docs(http_request):
    return render(http_request, 'pyha/swagger/swaggerui.html', {'static': settings.STA_URL, 'version': settings.VERSION})

project/pyha/templates/pyha/skipofficial/ask_information_tab.html
{% load i18n %}

<h3>{% trans "ask_additional_information_window" %}</h3>
<p>{% trans "ask_additional_information_window_description" %}</p>
{% for question in requestInformationChat_list %}
  {% if question.question %}
  <div class="panel panel-default" {% if question.user == user %} style="background-color:#d9edf7;" {% endif %}>
  <div class="panel-body"><p>{{question.date|date:"d.m.Y H:i"}} {{ question.name }} {% if question.target == 'admin' %} ({% trans 'admin_question' %}) {% else %} ({{ question.result.collectionName }}) {% endif %} {% trans "asked" %}&#10;&#13;{{question.message}}</p></div>
  </div>
  {% endif %}
  {% if question.question != True %}
  <div class="panel panel-default" {% if question.user == user %} style="background-color:#d9edf7;" {% endif %}>
  <div class="panel-body"><p>{{question.date|date:"d.m.Y H:i"}} {{ question.name }} {% trans 'inquiry' %} {% if question.target == 'admin' %} ({% trans 'admin_question' %}) {% else %} ({{ question.result.collectionName }}) {% endif %}{% trans "answered" %}&#10;&#13;{{question.message}}</p></div>
  </div>
  {% endif %}
{% endfor %}
<h4>{% trans "form_to_request_additional_information" %}</h4>
<form action="{% url 'pyha:question' %}" id="requestform" method="post">
  <div class="form-group">
    <input type="hidden" id="requestid" name="requestid" value={{userRequest.id}}>
    <input type="hidden" id="next" name="next" value="{{request.path}}?next=information">
    <span>{% trans 'ask_as_handler_of'%}</span>
    <select id="target" name="target">
    {% if role == "admin" %}
      <option value="admin">{% trans "as_admin" %}</option>
    {% else %}
    {% for collection in collections %}
      {% if collection.address in handles %}
      <option value="{{collection.address}}">{{collection.result.collectionName}}</option>
      {% endif %}
    {% endfor %}
    {% endif %}
    </select>
    <textarea class="form-control" rows="5" cols="70" id="reason" name="reason" required {% if userRequest.status == 3 or userRequest.status == 7 or userRequest.status == 8 or userRequest.frozen %} disabled {% endif %}></textarea>
    <button type="submit" id="submit" name="answer" value=2 class="btn btn-default btn-sm" {% if userRequest.status == 3 or userRequest.status == 7 or userRequest.status == 8 or userRequest.frozen %} disabled {% endif %}>{% trans "request_additional_information" %}</button>
  </div>
  {% csrf_token %}
</form>

project/pyha/templates/pyha/skipofficial/comments_tab.html
{% load i18n %}

<h3>{% trans "col_handler_comments_window" %}</h3>
<p>{% trans "col_handler_comments_window_description" %}</p>
<span>{% trans "this_section_is_only_visible_to_collection_handlers_not_request_owner" %}</hspan>
{% for requestHandlerChat in requestHandlerChat_list %}
<div class="panel panel-default">
  <div class="panel-body" {% if requestHandlerChat.user == user %} style="background-color:#d9edf7;" {% endif %}><p>{{requestHandlerChat.date|date:"d.m.Y H:i"}} {{ requestHandlerChat.name }}  {% if question.target == 'admin' %} ({% trans 'admin_question' %}) {% else %} ({{ requestHandlerChat.result.collectionName }}) {% endif %} {% trans "col_handler_said" %}&#10;&#13;{{requestHandlerChat.message}}</p></div>
</div>
{% endfor %}
<form action="{% url 'pyha:comment_handler' %}" id="commentform" method="post">
<div class="form-group">
  <input type="hidden" id="next" name="next" value="{{request.path}}?next=comments">
  <input type="hidden" id="requestid" name="requestid" value={{userRequest.id}}>
  <span>{% trans 'talk_as_handler_of' %}</span>
  <select id="target" name="target">
  {% if role == "admin" %}
  <option value="admin">{% trans "as_admin" %}</option>
  {% else %}
  {% for collection in collections %}
    {% if collection.address in handles %}
    <option value="{{collection.address}}">{{collection.result.collectionName}}</option>
    {% endif %}
  {% endfor %}
  {% endif %}
  </select>
  <textarea class="form-control" rows="5" cols="700" id="commentsForHandlers" name="commentsForHandlers" style="overflow:auto;resize:none" required {% if userRequest.status == 3 or userRequest.status == 7 or userRequest.status == 8 or userRequest.frozen %} disabled {% endif %} ></textarea>
  <button type="submit" id="submit" name="answer" value=1 class="btn btn-default btn-sm" {% if userRequest.status == 3 or userRequest.status == 7 or userRequest.status == 8 or userRequest.frozen %} disabled {% endif %}>{% trans "save" %}</button>
</div>
{% csrf_token %}
</form>

project/pyha/templates/pyha/skipofficial/contacts_tab.html
{% load i18n %}

<h3>{% trans "contact_window" %}</h3>
<p>{% trans "contact_window_description" %}</p>
<table class="table" style="width:100%">
  <tr style=color:black>
    <th>{% trans "full_name" %}</th>
    <th>{% trans "street_address" %}</th>
    <th>{% trans "postal_code" %}</th>
    <th>{% trans "post_office_name" %}</th>
    <th>{% trans "country" %}</th>
    <th>{% trans "email" %}</th>
    <th>{% trans "phone_number" %}</th>
    <th>{% trans "corporation/organization_name" %}</th>
    <th>{% trans "corporation_id" %}</th>
  </tr>
    {% for contact in contactlist %}
  <tr>
    <td>{{contact.personName}}</td>
    <td>{{contact.personStreetAddress}}</td>
    <td>{{contact.personPostalCode}}</td>
    <td>{{contact.personPostOfficeName}}</td>
    <td>{{contact.personCountry}}</td>
    <td>{{contact.personEmail}}</td>
    <td>{{contact.personPhoneNumber}}</td>
    <td>{{contact.personOrganizationName}}</td>
    <td>{{contact.personCorporationId}}</td>
  </tr>
    {% endfor %}
</table>

<button type="button" class="btn btn-default btn-sm" required data-toggle="modal" data-target="#myModalsens">{% trans "terms" %}</button>
<div class="modal fade" id="myModalsens" tabindex="-1" role="dialog" aria-labelledby="sensiModalLabel">
  <div class="modal-lg modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">{% trans "sensitive_and_other_terms" %}</h4>
        <form action="{% url 'pyha:newpdf' %}" onsubmit="this.source.value=document.getElementById('sens-content').outerHTML" method="post">
          <button type="submit" class="btn btn-default btn-sm">{% trans "as_pdf" %}</button>
          <input type="hidden" name="source" />
          {% csrf_token %}
        </form>
      </div>
      <div id="sens-content" class="modal-body">
        <div style="float:left;">
        <svg xmlns="http://www.w3.org/2000/svg"
          width="60" height="160" version="1.1" baseProfile="full"
          style="width: 60px; height: 160px; display: block;">
          <g transform="rotate(270)">
            <text textLength="160" fill="#777777" font-weight="700" font-size="50px" style="font-family: Arial, Helvetica, sans-serif;">
              <tspan x="-160" dy="50" >LAJI.FI</tspan>
            </text>
             </g>
          </svg>
        </div>
        <div style="margin-left:120px;margin-top:50px;">
          {% include sensitivity_terms %}
          <div style="margin-left:30px">
          <ul>
            <li><p class="model-field">{% trans 'contact_name' %} {{contactlist.0.personName}}</p></li>
            <ul>
            <li><p class="model-field">{% trans 'contact_street_address' %} {{contactlist.0.personStreetAddress}}</p></li>
            <li><p class="model-field">{% trans 'contact_postal' %} {{contactlist.0.personPostalCode}}</p></li>
            <li><p class="model-field">{% trans 'contact_post_office' %} {{contactlist.0.personPostOfficeName}}</p></li>
            <li><p class="model-field">{% trans 'contact_country' %} {{contactlist.0.personCountry}}</p></li>
            <li><p class="model-field">{% trans 'contact_email' %} {{contactlist.0.personEmail}}</p></li>
            <li><p class="model-field">{% trans 'contact_phone_number' %} {{contactlist.0.personPhoneNumber}}</p></li>
            {% if contactlist.0.personOrganizationName != "" %}
            <li><p class="model-field">{% trans 'contact_corporation' %} {{contactlist.0.personOrganizationName}}</p></li>
            {% endif %}
            {% if contactlist.0.personCorporationId != "" %}
            <li><p class="model-field">{% trans 'contact_corporation_id' %} {{contactlist.0.personCorporationId}}</p></li>
            {% endif %}
            </ul>
          </ul>
            {% for contact in contactlist|slice:"1:" %}
          <p style="width:100%;height:12px;"></p>
          <ul>
            <li><p class="model-field">{% trans 'additional_contact_name' %} {{contact.personName}}</p></li>
            <ul>
            <li><p class="model-field">{% trans 'contact_street_address' %} {{contact.personStreetAddress}}</p></li>
            <li><p class="model-field">{% trans 'contact_postal' %} {{contact.personPostalCode}}</p></li>
            <li><p class="model-field">{% trans 'contact_post_office' %} {{contact.personPostOfficeName}}</p></li>
            <li><p class="model-field">{% trans 'contact_country' %} {{contact.personCountry}}</p></li>
            <li><p class="model-field">{% trans 'contact_email' %} {{contact.personEmail}}</p></li>
            <li><p class="model-field">{% trans 'contact_phone_number' %} {{contact.personPhoneNumber}}</p></li>
            {% if contact.personOrganizationName != "" %}
            <li><p class="model-field">{% trans 'contact_corporation' %} {{contact.personOrganizationName}}</p></li>
            {% endif %}
            {% if contact.personCorporationId != "" %}
            <li><p class="model-field">{% trans 'contact_corporation_id' %} {{contact.personCorporationId}}</p></li>
            {% endif %}
            </ul>
          </ul>
            {% endfor %}
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" id=>{% trans "exit" %}</button>
      </div>
    </div>
  </div>
</div>

project/pyha/templates/pyha/skipofficial/filters_tab.html
{% load i18n %}

<h3>{% trans "filter_window" %}</h3>
<p>{% trans "filter_window_description" %}</p>
{% if filters %}
  <a style="padding-left:8px;" href="{{ filter_link }}" target="_blank">{% trans "show_in_portal" %}</a>
  <table class="table" style="width:100%">
    <tr style=color:black>
      <th>{% trans "filter" %}</th>
      <th>{% trans "values" %}</th>
    </tr>
    {% for filter in filters %}
    <tr>
      <td rowspan={{filter.1|length}}>{{ filter.2 }}</td>
      {% for f in filter.1 %}
      <td>{{ f }}</td>
    </tr>
    <tr>
      {% endfor %}
    </tr>
    {% endfor %}
  </table>
  {% if coordinates %}
    <div id="filtermap"></div>
  {% endif %}
{% else %}
  <strong>{% trans "no_filters" %}.</strong>
{% endif %}