project/config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.i18n import JavaScriptCatalog
from django.conf.urls.static import static
from django.conf import settings
from pyha import decorator, views


urlpatterns = [
    url(r'^', include('pyha.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(domain='djangojs', packages=['pyha']),
        name='javascript-catalog'),
]

urlpatterns += decorator.required(decorator.admin_required_and_force_english, [
    url(r'^{0}/logout/?$'.format(settings.SECRET_ADMIN_SUB_DIR), views.logout.logout),
    url(r'^{0}/'.format(settings.SECRET_ADMIN_SUB_DIR), admin.site.urls)
])

project/pyha/urls.py
from django.conf.urls import url
from django.conf import settings
from django.views.generic import RedirectView
from config.timers import *
from pyha.views import api, api_statistics, api_docs, index, requestform, requestview, logout, ajax, usersettings

app_name = 'pyha'
urlpatterns = [
    url(r'^pyha/?$', index.pyha, name='pyha'),
    url(r'^/?$', index.index, name='root'),
    url(r'^index/?$', index.pyha, name='index'),
    url(r'^login/?$', index.index, name='login'),
    url(r'^groupdeleterequest/?$', index.group_delete_request, name='group_delete_request'),
    url(r'^logout/?$', logout.logout, name='logout'),
    url(r'^settings/?$', usersettings.usersettings, name='usersettings'),
    url(r'^ajax/getCollection/?$', ajax.get_collection_ajax, name='get_collection_ajax'),
    url(r'^ajax/getSummary/?$', ajax.get_summary_ajax, name='get_summary_ajax'),
    url(r'^ajax/createContact/?$', ajax.create_contact_ajax, name='create_contact_ajax'),
    url(r'^ajax/removeCollection/?$', ajax.remove_collection_ajax, name='remove_collection_ajax'),
    url(r'^ajax/getDescription/?$', ajax.get_description_ajax, name='get_description_ajax'),
    url(r'^ajax/setDescription/?$', ajax.set_description_ajax, name='set_description_ajax'),
    url(r'^ajax/getRequestList/?$', index.get_request_list_ajax, name='get_request_list_ajax'),
    url(r'^approve/?$', requestform.approve_terms, name='approve'),
    url(r'^request/[1-9][0-9]*/?$', requestview.show_request, name='show_request'),
    url(r'^description/?$', requestview.change_description, name='change_description'),
    url(r'^answer/?$', requestview.answer, name='answer'),
    url(r'^question/?$', requestview.question, name='question'),
    url(r'^groupanswer/?$', requestview.group_answer, name='group_answer'),
    url(r'^information/?$', requestview.information, name='information'),
    url(r'^chatEntryFileDownload/?$', requestview.chat_entry_file_download, name='chat_entry_file_download'),
    url(r'^commentHandler/?$', requestview.comment_handler, name='comment_handler'),
    url(r'^sendEmail/?$', requestview.send_email, name='send_email'),
    url(r'^initializeDownload/?$', requestview.initialize_download, name='initializeDownload'),
    url(r'^downloadLink/?$', ajax.download_link, name='requestDownload'),
    url(r'^gisDownloadStatus/(?P<download_id>[^/]+)/?$', ajax.gis_download_status, name='gis_download_status'),
    url(r'^gisDownloadOutput/(?P<download_id>[^/]+)/?$', ajax.gis_download_output, name='gis_download_output'),
    url(r'^apiKey/?$', ajax.get_api_key, name='get_api_key'),
    url(r'^saveUserSettings/?$', usersettings.save_user_settings, name='save_user_settings'),
    url(r'^savePyhaSettings/?$', usersettings.save_pyha_settings, name='save_pyha_settings'),
    url(r'^newpdf/?$', api.new_pdf, name='newpdf'),
    url(r'^api/request/?$', api.receiver, name='receiver'),
    url(r'^api/download/(?P<link>[^/]+)/?$', api.download, name='download'),
    url(r'^api/newcount/?$', api.new_count, name='new_count'),
    url(r'^{0}/?$'.format(settings.SECRET_STATUS_SUB_DIR), api.status, name='status'),
    url(r'^api/swagger.json$', api_docs.api_spec, name='api_spec'),
    url(r'^api/docs/?$', api_docs.api_docs, name='swagger-ui'),
    url(r'^api/statistics/countByYear/?$', api_statistics.request_count_by_year, name='count_by_year'),
    url(r'^api/statistics/collectionCounts/?$', api_statistics.collection_counts, name='collection_counts'),
    url(r'^api/statistics/reasonCounts/?$', api_statistics.request_reason_counts, name='reason_counts'),
    url(r'^api/statistics/reasonPhraseCounts/?$', api_statistics.request_reason_phrase_counts, name='reason_phrase_counts'),
    url(r'^api/statistics/partyInvolvementCounts/?$', api_statistics.request_party_involvement_counts, name='party_involvement_counts'),
    url(r'^role/?$', logout.change_role, name='change_role'),
    url(r'^freezeRequest/?$', requestview.freeze, name='freeze'),
    url(r'^refreshCollectionsCache/?$', requestview.refresh_collections_cache, name='refresh_collections_cache'),
    url(r'^lang/?$', logout.change_lang, name='set_language'),
    url(r'^handler-manual.pdf$', RedirectView.as_view(
        url='https://cdn.laji.fi/files/pyha/Aineistopyyntöjärjestelmä_ohje_käsittelijoille_2022.pdf',
        permanent=False
    ), name='handler_manual')
]

project/pyha/views/ajax.py
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, StreamingHttpResponse
from django.shortcuts import render
from django.conf import settings
from pyha.database import create_request_view_context, check_all_collections_removed, is_downloadable
from pyha.localization import check_language
from pyha.login import logged_in, is_allowed_to_view, is_request_owner, is_admin_frozen
from pyha.models import Request, Collection, StatusEnum
from pyha.log_utils import changed_by_session_user
import requests
from http import HTTPStatus

from pyha.view_utils import get_default_laji_api_headers


def download_link(http_request):
    if http_request.method == 'POST':
        if not logged_in(http_request):
            return HttpResponse(status=HTTPStatus.UNAUTHORIZED)
        requestId = http_request.POST.get('requestid')
        if not is_request_owner(http_request, requestId):
            return HttpResponse(status=HTTPStatus.FORBIDDEN)
        userRequest = Request.objects.get(id=requestId)
        if is_admin_frozen(http_request, userRequest):
            return HttpResponse(status=HTTPStatus.LOCKED)
        if not (userRequest.status == 8 and is_downloadable(http_request, userRequest)):
            return HttpResponse(status=HTTPStatus.BAD_REQUEST)

        userRequest.downloaded = True
        userRequest.changedBy = changed_by_session_user(http_request)
        userRequest.save()

        file_type = http_request.POST.get('fileType', '?')
        geometry = http_request.POST.get('geometry', '?')
        CRS = http_request.POST.get('CRS', '?')
        laji_id = userRequest.lajiId
        person_token = http_request.session['token']

        if file_type == 'GIS':
            params = {
                'geometryType': geometry,
                'crs': CRS
            }
            headers = get_default_laji_api_headers(http_request)
            url = '{}geo-convert/{}'.format(settings.LAJIAPI_URL, laji_id)
            r = requests.get(url, params=params, headers=headers)

            if not r.ok:
                return _get_geoconvert_error_response(r)

            return HttpResponseRedirect(reverse('pyha:gis_download_status', args=(r.json(),)))
        else:
            link = '{}{}?personToken={}'.format(settings.LAJIDOW_URL, laji_id, person_token)
            return JsonResponse({'status': 'complete', 'downloadUrl': link})

    return HttpResponse(status=HTTPStatus.METHOD_NOT_ALLOWED)


def gis_download_status(http_request, download_id):
    if http_request.method == 'GET':
        headers = get_default_laji_api_headers(http_request)
        url = '{}geo-convert/status/{}'.format(settings.LAJIAPI_URL, download_id)
        r = requests.get(url, headers=headers)

        if not r.ok:
            return _get_geoconvert_error_response(r)

        status_obj = r.json()
        status = status_obj['status']
        response = {
            'status': status,
            'progressPercent': status_obj['progress_percent'],
            'statusUrl': reverse('pyha:gis_download_status', args=(download_id,)),
            'downloadUrl': reverse('pyha:gis_download_output', args=(download_id,)) if status == 'complete' else None
        }

        return JsonResponse(response)

    return HttpResponse(status=HTTPStatus.METHOD_NOT_ALLOWED)


def gis_download_output(http_request, download_id):
    if http_request.method == 'GET':
        headers = get_default_laji_api_headers(http_request)
        url = '{}geo-convert/output/{}'.format(settings.LAJIAPI_URL, download_id)
        r = requests.get(url, headers=headers, stream=True)

        response = StreamingHttpResponse(
            r.raw,
            content_type=r.headers.get('content-type'),
            status=r.status_code,
            reason=r.reason
        )

        content_disposition = r.headers.get('content-disposition')
        if content_disposition:
            response['Content-Disposition'] = content_disposition

        return response

    return HttpResponse(status=HTTPStatus.METHOD_NOT_ALLOWED)


def get_api_key(http_request):
    if http_request.method == 'POST':
        if not logged_in(http_request):
            return HttpResponse(status=HTTPStatus.UNAUTHORIZED)
        requestId = http_request.POST.get('requestid')
        if not is_request_owner(http_request, requestId):
            return HttpResponse(status=HTTPStatus.FORBIDDEN)
        userRequest = Request.objects.get(id=requestId)
        if is_admin_frozen(http_request, userRequest):
            return HttpResponse(status=HTTPStatus.LOCKED)
        if not (userRequest.status == 8 and is_downloadable(http_request, userRequest)):
            return HttpResponse(status=HTTPStatus.BAD_REQUEST)

        userRequest.downloaded = True
        userRequest.changedBy = changed_by_session_user(http_request)
        userRequest.save()

        laji_id = userRequest.lajiId
        person_token = http_request.session['token']

        response = requests.get('{}warehouse/api-keys/{}'.format(settings.LAJIAPI_URL, laji_id),
                                params={'personToken': person_token, 'access_token': settings.LAJIAPI_TOKEN},
                                timeout=settings.SECRET_TIMEOUT_PERIOD
                                )
        if not response.ok:
            return HttpResponse(status=HTTPStatus.BAD_GATEWAY)

        api_key = response.json()
        if 'apiKey' not in api_key:
            return HttpResponse(status=HTTPStatus.NOT_FOUND)

        return JsonResponse({
            'apiKey': api_key['apiKey'],
            'apiKeyExpires': api_key['apiKeyExpires']
        })

    return HttpResponse(status=HTTPStatus.METHOD_NOT_ALLOWED)


def get_description_ajax(http_request):
    if http_request.method == 'POST' and http_request.POST.get('requestid'):
        if check_language(http_request):
            return HttpResponse(reverse(http_request.get_full_path()), status=310)
        if not logged_in(http_request):
            return HttpResponse(reverse('pyha:root'), status=310)
        requestId = http_request.POST.get('requestid')
        if not is_allowed_to_view(http_request, requestId):
            return HttpResponse(reverse('pyha:root'), status=310)
        userRequest = Request.objects.get(id=requestId)
        context = create_request_view_context(requestId, http_request, userRequest)
        return render(http_request, 'pyha/base/ajax/requestheader.html', context)
    return HttpResponse(reverse('pyha:root'), status=310)


def set_description_ajax(http_request):
    if http_request.method == 'POST':
        if not logged_in(http_request):
            return HttpResponse(reverse('pyha:root'), status=310)
        requestId = http_request.POST.get('requestid')
        if not is_request_owner(http_request, requestId):
            return HttpResponse(reverse('pyha:root'), status=310)
        userRequest = Request.objects.get(id=requestId)
        if is_admin_frozen(http_request, userRequest):
            return HttpResponse(reverse('pyha:root'), status=310)
        userRequest.description = http_request.POST.get('description')
        userRequest.changedBy = changed_by_session_user(http_request)
        userRequest.save()
        return HttpResponse(status=200)
    return HttpResponse(reverse('pyha:root'), status=310)


def get_collection_ajax(http_request):
    if http_request.method == 'POST' and http_request.POST.get('requestid'):
        if check_language(http_request):
            return HttpResponse(reverse(http_request.get_full_path()), status=310)
        if not logged_in(http_request):
            return HttpResponse(reverse('pyha:root'), status=310)
        requestId = http_request.POST.get('requestid')
        if not is_allowed_to_view(http_request, requestId):
            return HttpResponse(reverse('pyha:root'), status=310)
        userRequest = Request.objects.get(id=requestId)
        if is_admin_frozen(http_request, userRequest):
            return HttpResponse(reverse('pyha:root'), status=310)
        if(userRequest.status == StatusEnum.APPROVETERMS_WAIT):
            context = create_request_view_context(requestId, http_request, userRequest)
            return render(http_request, 'pyha/requestform/ajax/requestformcollection.html', context)
    return HttpResponse(reverse('pyha:root'), status=310)


def get_summary_ajax(http_request):
    if http_request.method == 'POST' and http_request.POST.get('requestid'):
        if check_language(http_request):
            return HttpResponse(reverse(http_request.get_full_path()), status=310)
        if not logged_in(http_request):
            return HttpResponse(reverse('pyha:root'), status=310)
        requestId = http_request.POST.get('requestid')
        if not is_allowed_to_view(http_request, requestId):
            return HttpResponse(reverse('pyha:root'), status=310)
        userRequest = Request.objects.get(id=requestId)
        if is_admin_frozen(http_request, userRequest):
            return HttpResponse(reverse('pyha:root'), status=310)
        if(userRequest.status == StatusEnum.APPROVETERMS_WAIT):
            context = create_request_view_context(requestId, http_request, userRequest)
            return render(http_request, 'pyha/requestform/ajax/requestformsummary.html', context)
    return HttpResponse(reverse('pyha:root'), status=310)


def create_contact_ajax(http_request):
    if http_request.method == 'POST' and http_request.POST.get('requestid') and http_request.POST.get('id'):
        if check_language(http_request):
            return HttpResponse(reverse(http_request.get_full_path()), status=310)
        if not logged_in(http_request):
            return HttpResponse(reverse('pyha:root'), status=310)
        requestId = http_request.POST.get('requestid')
        if not is_request_owner(http_request, requestId):
            return HttpResponse(reverse('pyha:root'), status=310)
        userRequest = Request.objects.get(id=requestId)

project/pyha/views/api_docs.py
from apispec import APISpec
from apispec import BasePlugin
from apispec.yaml_utils import load_operations_from_docstring
from django.http import JsonResponse
from django.shortcuts import render
from django.conf import settings
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from pyha.views.api_statistics import request_count_by_year, collection_counts, request_reason_counts, \
    request_reason_phrase_counts, request_party_involvement_counts


class PyhaPlugin(BasePlugin):
    def path_helper(self, path, operations, func, **kwargs):
        """Path helper that parses docstrings for operations. Adds a
        ``func`` parameter to `apispec.APISpec.path`.
        """
        operations.update(load_operations_from_docstring(func.__doc__))


def get_spec():
    spec = APISpec(
        title="Pyha API",
        version="1.0.0",
        openapi_version="3.0.2",
        plugins=[PyhaPlugin()]
    )

    spec.path(path=reverse('pyha:count_by_year'), func=request_count_by_year)
    spec.path(path=reverse('pyha:collection_counts'), func=collection_counts)
    spec.path(path=reverse('pyha:reason_counts'), func=request_reason_counts)
    spec.path(path=reverse('pyha:reason_phrase_counts'), func=request_reason_phrase_counts)
    spec.path(path=reverse('pyha:party_involvement_counts'), func=request_party_involvement_counts)

    return spec


@csrf_exempt
def api_spec(http_request):
    return JsonResponse(get_spec().to_dict())


@csrf_exempt
def api_docs(http_request):
    return render(http_request, 'pyha/swagger/swaggerui.html', {'static': settings.STA_URL, 'version': settings.VERSION})

project/pyha/templates/pyha/requestview/tabs/admin_communications.html
{% load i18n %}

{% if handler_groups %}
<form action="{% url 'pyha:refresh_collections_cache' %}" id="refreshform" method="post">
  <h3 id="communications_header">
    {% trans "admin_communications_window" %}
    <input type="hidden" id="next" name="next" value="{{request.path}}?next=communications">
    <button type="submit" id="submit_refresh" name="send" value=1 class="btn btn-default btn-sm">{% trans "admin_refresh_collections_cache" %}</button>
    {% csrf_token %}
  </h3>
  <p>{% trans "admin_communications_window_description" %}</p>
</form>
  {% if com_last_automated_send_email %}
    <div class="form-group stale-form">
      <h>{% trans "admin_automated_emails_sent_last_time" %}: {{ com_last_automated_send_email|date:"d.m.Y    H:i"}}</h>
    </div>
  {% endif %}
<form action="{% url 'pyha:send_email' %}" id="requestform" method="post">
  <table id="communications_table" class="table" style="width:100%;">
    <tr>
      <th>{% trans "admin_communications_collections" %}</th>
      <th style="text-align:right;">{% trans "admin_communications_handlers" %}</th>
      <th>{% trans "admin_communications_state" %}</th>
      <th>{% trans "admin_send_email" %}</th>
      <th>{% trans "admin_communications_email" %}</th>
    </tr>
    {% for group in handler_groups %}
      {% if group.handlers.0.id == 'None' %}
        <tr>
          <td colspan=2 style="vertical-align: middle;">
            <table class="collection-group-error" style="width:100%">
              <tr>
                <td style="border-bottom:0; width:100%">
                {% for collection in group.collections %}
                  <p style="white-space: nowrap;"><a href="{{tun_link}}{{collection.id}}" target="_blank">{{ collection.collectionName }}</a></p>
                {% endfor %}
                </td>
                <td style="border-bottom:0;">
                {% for handler in group.handlers %}
                  <p style="white-space: nowrap;">{% trans 'admin_name_is_none' %}</p>
                {% endfor %}
                </td>
              </tr>
            </table>
          </td>
          <td style="vertical-align: middle; line-height: 40px;">
            <p style="margin-bottom: 16px; color:red;">{% trans "admin_collections_missing_handler" %}</p>
          </td>
          <td></td>
          {% if forloop.first %}
          <td rowspan="{{handler_groups|length}}"  style="border:0px; border-top: 1px solid #ddd; border-left: 1px solid #ddd;">
              <div class="form-group">
                <input type="hidden" id="requestid" name="requestid" value={{userRequest.id}}>
                <input type="hidden" id="next" name="next" value="{{request.path}}?next=communications">
                <table style="width:100%;">
                <tr>
                  <td style="border:0px;">{% trans "email_sender" %}</td>
                  <td style="width:100%; border:0px;"><input type="text" id="com_email_sender" name="com_email_sender" value="{{ com_email_template.sender }}" style="width:100%;padding:6px 12px;"></td>
                </tr>
                <tr>
                  <td style="border:0px;">{% trans "email_header" %}</td>
                  <td style="width:100%; border:0px;"><input type="text" id="com_email_header" name="com_email_header" value="{{ com_email_template.header }}" style="width:100%;padding:6px 12px;"></td>
                </tr>
                </table>
                <textarea class="form-control" rows="15" cols="70" id="com_email_content" name="com_email_content">{{ com_email_template.content }}</textarea>
                <button type="submit" id="submit_email" name="send" value=1 class="btn btn-default btn-sm">{% trans "admin_send" %}</button>
              </div>
          </td>
          {% endif %}
        </tr>
      {% else %}
        <tr>
          <td colspan=2 style="vertical-align: middle;">
            <table class="collection-group" style="width:100%">
              <tr>
                <td style="border-bottom:0; width:100%">
                {% for collection in group.collections %}
                  <p style="white-space: nowrap;"><a href="{{tun_link}}{{collection.id}}" target="_blank">{{ collection.collectionName }}</a></p>
                {% endfor %}
                </td>
                <td style="border-bottom:0;">
                {% for handler in group.handlers %}
                  <p style="white-space: nowrap; text-align:right;">[{{ handler.id }}] {{ handler.name }} ({{ handler.email }})</p>
                {% endfor %}
                </td>
              </tr>
            </table>
          </td>
          <td style="vertical-align: middle; line-height: 40px;">
            {% for handler in group.handlers %}
              {% if handler.mailed %}
                <p style="margin-bottom: 10px;">{% trans "emailed" %}</p>
              {% else %}
                <p style="margin-bottom: 10px;">{% trans "not_emailed" %}</p>
              {% endif %}
            {% endfor %}
              <div style="margin-bottom: 16px;"></div>
          </td>
          <td style="vertical-align: middle; line-height: 40px;">
            {% for handler in group.handlers %}
              <p style="white-space: nowrap;"><input {% if handler.mailed %} disabled {% endif %} onChange="enableCommunicationsEmail()" type="checkbox" name="email_id_{{ handler.id }}" value="{{ handler.email }}" style="margin-top: 0px; margin-left: 15px; vertical-align: middle;"></p>
            {% endfor %}
              <div style="margin-bottom: 16px;"></div>
          </td>
          {% if forloop.first %}
          <td rowspan="{{handler_groups|length}}"  style="border:0px; border-top: 1px solid #ddd; border-left: 1px solid #ddd;">
              <div class="form-group">
                <input type="hidden" id="requestid" name="requestid" value={{userRequest.id}}>
                <input type="hidden" id="next" name="next" value="{{request.path}}?next=communications">
                <table style="width:100%;">
                <tr>
                  <td style="border:0px;">{% trans "email_sender" %}</td>
                  <td style="width:100%; border:0px;"><input type="text" id="com_email_sender" name="com_email_sender" value="{{ com_email_template.sender }}" style="width:100%;padding:6px 12px;"></td>
                </tr>
                <tr>
                  <td style="border:0px;">{% trans "email_header" %}</td>
                  <td style="width:100%; border:0px;"><input type="text" id="com_email_header" name="com_email_header" value="{{ com_email_template.header }}" style="width:100%;padding:6px 12px;"></td>
                </tr>
                </table>
                <textarea class="form-control" rows="15" cols="70" id="com_email_content" name="com_email_content">{{ com_email_template.content }}</textarea>
                <button type="submit" id="submit_email" name="send" value=1 class="btn btn-default btn-sm">{% trans "admin_send" %}</button>
              </div>
          </td>
          {% endif %}
        </tr>
      {% endif %}
    {% endfor %}
  </table>
  {% csrf_token %}
</form>
{% else %}
<h3>{% trans "admin_communications_window" %}</h3>
<p>{% trans "admin_communications_window_description" %}</p>
<strong>{% trans "no_communications" %}</strong>
{% endif %}

project/pyha/templates/pyha/requestview/tabs/arguments.html
{% load i18n %}

<h3>{% trans "argument_window" %}</h3>
<p>{% trans "argument_window_description" %}</p>
{% include 'pyha/common/argument_table.html' %}

project/pyha/templates/pyha/requestview/tabs/ask_information.html
{% load i18n %}

<h3>{% trans "ask_additional_information_window" %}</h3>
<p>{% trans "ask_additional_information_window_description" %}</p>
{% for question in requestInformationChat_list %}
  {% if question.question %}
  <div class="panel panel-default" {% if question.user == user %} style="background-color:#d9edf7;" {% endif %}>
    <div class="panel-body">
      <p>{{question.date|date:"d.m.Y H:i"}} {{ question.name }} {% if question.target == 'admin' %} ({% trans 'admin_question' %}) {% else %} ({{ question.result.collectionName }}) {% endif %} {% trans "asked" %}&#10;&#13;{{question.message}}</p>
      {% include "pyha/requestview/shared/chat_entry_file_download.html" with chatEntry=question %}
    </div>
  </div>
  {% endif %}
  {% if question.question != True %}
  <div class="panel panel-default" {% if question.user == user %} style="background-color:#d9edf7;" {% endif %}>
  <div class="panel-body">
    <p>{{question.date|date:"d.m.Y H:i"}} {{ question.name }} {% if question.target == 'admin' %} ({% trans 'admin_question' %}) {% else %} ({{ question.result.collectionName }}) {% endif %} {% trans 'inquiry' %} {% trans "answered" %}&#10;&#13;{{question.message}}</p>
    {% include "pyha/requestview/shared/chat_entry_file_download.html" with chatEntry=question %}
  </div>
  </div>
  {% endif %}
{% endfor %}
<h4>{% trans "form_to_request_additional_information" %}</h4>
<form action="{% url 'pyha:question' %}" id="ask-information-form" method="post" enctype="multipart/form-data">
  <div class="form-group">
    <input type="hidden" id="requestid" name="requestid" value={{userRequest.id}}>
    <input type="hidden" id="next" name="next" value="{{request.path}}?next=information">
    <span>{% trans 'ask_as_handler_of'%}</span>
    <select id="target" name="target">
    {% if role == "admin" %}
      <option value="admin">{% trans "as_admin" %}</option>
    {% else %}
    {% for collection in collections %}
      {% if collection.address in handles %}
      <option value="{{collection.address}}">{{collection.result.collectionName}}</option>
      {% endif %}
    {% endfor %}
    {% endif %}
    </select>
    <textarea class="form-control" rows="5" cols="70" id="reason" name="reason" required {% if userRequest.status == 3 and role != 'admin' or userRequest.status == 7 and role != 'admin' or userRequest.status == 8 and role != 'admin' %} disabled {% endif %}></textarea>
    <div id="reason_count" class="textarea-character-count"></div>
    <div style="margin: 10px 0">
      <label for="reasonFile">{% trans "add_pdf_attachment" %}</label>
      <input type="file" id="reasonFile" name="reasonFile" accept="application/pdf">
    </div>
    <button type="submit" id="submit" name="answer" value=2 class="btn btn-default btn-sm" {% if userRequest.status == 3 and role != 'admin' or userRequest.status == 7 and role != 'admin' or userRequest.status == 8 and role != 'admin' %} disabled {% endif %}>{% trans "request_additional_information" %}</button>
  </div>
  {% csrf_token %}
</form>

project/pyha/templates/pyha/requestview/tabs/decision.html
{% load i18n %}
{% load pyha_tags %}

<h3>{% trans "decision_window" %}</h3>
<p>{% trans "decision_window_description" %}</p>
  <table class="table" style="width:100%">
    <tr style=color:black>
      <th>{% trans "collection_name" %}</th>
      <th>{% trans "state_of_processing" %}</th>
      <th>{% trans "collection_decision_arguments" %}</th>
    </tr>
    {% for collection in collections %}
      {% if collection.status == 1 %}
      <tr class="info clickable-row">
      {% elif collection.status == 3 %}
      <tr class="danger clickable-row">
      {% elif collection.status == 4 %}
      <tr class="success clickable-row">
      {% else %}
      <tr>
      {% endif %}
      <td><a href="{{tun_link}}{{collection.address}}" target="_blank">{{collection.result.collectionName}}</a></td>
      <td>{% translateCollectionStatus collection.status role collection.address handles %}</td>
      <td>{% if collection.decisionExplanation %}<p>{{collection.decisionExplanation}}</p>{% endif %}</td>
    {% endfor %}
  </table>

project/pyha/templates/pyha/requestview/tabs/filters.html
{% load i18n %}

<h3>{% trans "filter_window" %}</h3>
<p>{% trans "filter_window_description" %}</p>
{% include 'pyha/common/filter_table.html' %}